### ISSUE TITLE
Add feature to add dashed border around a bar

### ISSUE THREAD

**Issue by SayuruSandaru** [imaNNeo/fl_chart#1144]
Please enable to add a feature to add dashed border to a bar in the barchart. This can useful when the user need to present a predicted data in the future. Below is a sample graph that I took from an app.

![3-mint-ios (2)](https://user-images.githubusercontent.com/28390211/189798755-3eeb4ab6-c8f0-4058-afa1-d5d2cbd040b8.png)

**Comment by PrabeshPP** [comment]
@imaNNeoFighT Is anyone working on this issue? If not ,I am interested in it.

**Comment by Dartek12** [comment]
Related issue: https://github.com/imaNNeo/fl_chart/issues/1194

**Comment by k0psutin** [comment]
Hey! 

I have been working with Flutter for about a year now. I've been using `fl_chart` in few of my projects. I really like this project so I would like to contribute to the project and I would like to do this feature. :) 

I was thinking that, we could add `dashArray` parameter to `BarChartRodData` and use that together with `drawPath`.

I'll read up on the contributing guidelines on the way. :)

**Comment by k0psutin** [comment]
@imaNNeo Is it intentional that, the border is drawn before `drawStackItemBorderStroke`? If the border is drawn before `drawStackItemBorderStroke` then the `BarChartRodStackItem` will eat away some of the border, see pic:

![Näyttökuva 2023-10-13 211822](https://github.com/imaNNeo/fl_chart/assets/48412269/7dba0360-b83c-4b47-97a7-05f6d6d72508)

It's only noticeable on really thick borders. On the other hand, if we draw the border last, we will get:


![Näyttökuva 2023-10-13 212154](https://github.com/imaNNeo/fl_chart/assets/48412269/2b4aad31-8b21-4258-ab22-b1a5a5330eda)![Näyttökuva 2023-10-13 212229](https://github.com/imaNNeo/fl_chart/assets/48412269/fe1eee13-a0d2-44ef-90b2-4fceb89324d7)

**Comment by imaNNeo** [comment]
Landed in [0.65.0](https://github.com/imaNNeo/fl_chart/releases/tag/0.65.0)
Check it out!

**Comment by imaNNeo** [comment]
> @imaNNeo Is it intentional that, the border is drawn before `drawStackItemBorderStroke`? If the border is drawn before `drawStackItemBorderStroke`, then the `BarChartRodStackItem` will eat away some of the border, see pic:
> 

I can't recall the intention behind that
